name: NameTags
main: org.kitteh.nametags.NameTags
description: ${project.description}
author: mbaxter
url: http://kitteh.org
version: '${project.version}'
softdepend: [TagAPI]
commands:
  nametags:
    usage: /nametags reload
    permission: nametags.reload
permissions:
  nametags.color.black:
    default: false
  nametags.color.dark_blue:
    default: false
  nametags.color.dark_green:
    default: false
  nametags.color.dark_aqua:
    default: false
  nametags.color.dark_purple:
    default: false
  nametags.color.dark_red:
    default: false
  nametags.color.gold:
    default: false
  nametags.color.gray:
    default: false
  nametags.color.dark_gray:
    default: false
  nametags.color.blue:
    default: false
  nametags.color.green:
    default: false
  nametags.color.aqua:
    default: false
  nametags.color.red:
    default: false
  nametags.color.light_purple:
    default: false
  nametags.color.yellow:
    default: false
  nametags.color.white:
    default: false
  nametags.color.random:
    default: false
    description: All colors possible.
    children:
      nametags.color.black: true
      nametags.color.dark_blue: true
      nametags.color.dark_green: true
      nametags.color.dark_aqua: true
      nametags.color.dark_purple: true
      nametags.color.dark_red: true
      nametags.color.gold: true
      nametags.color.gray: true
      nametags.color.dark_gray: true
      nametags.color.blue: true
      nametags.color.green: true
      nametags.color.aqua: true
      nametags.color.red: true
      nametags.color.light_purple: true
      nametags.color.yellow: true
      nametags.color.white: true
  nametags.format.magic:
    default: false
  nametags.format.bold:
    default: false
  nametags.format.strikethrough:
    default: false
  nametags.format.underline:
    default: false
  nametags.format.italic:
    default: false
  nametags.seenalways:
    default: false
    description: Seen even with onlySeeSame set to true
  nametags.reload:
    default: op
    description: Reload shtuff
  nametags.*:
    default: false
    description: Everything.
    children:
      nametags.color.black: true
      nametags.color.dark_blue: true
      nametags.color.dark_green: true
      nametags.color.dark_aqua: true
      nametags.color.dark_purple: true
      nametags.color.dark_red: true
      nametags.color.gold: true
      nametags.color.gray: true
      nametags.color.dark_gray: true
      nametags.color.blue: true
      nametags.color.green: true
      nametags.color.aqua: true
      nametags.color.red: true
      nametags.color.light_purple: true
      nametags.color.yellow: true
      nametags.color.white: true
      nametags.format.magic: true
      nametags.format.bold: true
      nametags.format.strikethrough: true
      nametags.format.underline: true
      nametags.format.italic: true
# vim: ts=2 sts=2 sw=2 et
