name: NameTags
main: org.kitteh.nametags.NameTags
description: ${project.description}
author: mbaxter
url: http://kitteh.org
version: '${project.version}'
softdepend: [TagAPI]
commands:
  nametags:
    usage: /nametags reload
    permission: nametags.reload
permissions:
  nametags.reload:
    default: op
    description: Reload shtuff
# vim: ts=2 sts=2 sw=2 et
